### ISSUE TITLE
apply body styles

### ISSUE THREAD

**Issue by andrewrk** [Automattic/juice#15]
Input:

``` html
<html>
  <head>
  </head>
  <body>
    <div>div1</div>
    <div>div2</div>
  </body>
</html>
```

``` css
body {
  font-family: sans-serif;
}
```

output

``` html
<div>div1</div>
<div>div2</div>
```

expected output

``` html
<div style="font-family: sans-serif;">div1</div>
<div style="font-family: sans-serif;">div2</div>
```
