### ISSUE TITLE
* selector styles are added to HTML and META tags 

### ISSUE THREAD

**Issue by duanefields** [Automattic/juice#156]
Styles with the * selector probably should not be added to HTML, HEAD, and META tags, along with any other non visual tags

```css
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}
</style>
```

```html
<!doctype html>
<html style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, 
sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<head style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, 
sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
<meta name="viewport" content="width=device-width" style="font-family: 
'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 
100%; line-height: 1.6em; margin: 0; padding: 0;">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" 
style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, 
sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
</head>
