### ISSUE TITLE
1.11.0 has breaking specificity issues in some cases where !important is used

### ISSUE THREAD

**Issue by santiagoaguiar** [Automattic/juice#210]
I have a template with the following media query:
```css
@media only screen and (max-width: 640px) {
        body {
            padding: 0 !important;
        }
        .container {
            padding: 0 !important;
            width: 100% !important;
        }
        .content {
            padding: 0 !important;
        }

        .invoice {
            width: 100% !important;
        }
        .content-middel-space{
            padding:0px 10px !important;
        }
        .gray-bottom-bkg{
            background-color: #FFF !important;
         }
    }
```

And a css that says:
```css
...
 .content {
     padding: 20px;
}
...
```

For some reason, after 1.11 was installed, the .content elemnet has an inline style of `padding: 0`, but it should be `20px`. This breaks my templates (actually, I didn't update `juice`, but depends on `email-templates` which depends on ^1.0.0...)

I'll admit I'm not 100% sure that the changes for 1.11 are the culprits, but it's my best guess at the moment. I'll keep investigating.

Thanks!
