### ISSUE TITLE
Declaration order of overridden properties should be maintained

### ISSUE THREAD

**Issue by bago** [Automattic/juice#218]
Sometimes the property declaration order is important for the final result and juice does the wrong thing.

here the html
```html
<div class="a b"></div>
```

```css
.b {
  padding: 20px;
  padding-top: 10px;
  color: red;
}
.a {
  padding-top: 0;
  padding: 5px;
  padding: 10px;
}
```

expected:
```html
<div class="a b" style="color: red; padding-top: 0; padding: 10px;"></div>
```

actual
```html
<div class="a b" style="padding: 10px; padding-top: 0; color: red;"></div>
```

in the actual the padding top is 0, while the expected result is the padding-top to be 10px.
