### ISSUE TITLE
Apply @media queries inline

### ISSUE THREAD

**Issue by mitar** [Automattic/juice#244]
It seems this package currently allow only copying over `@media` queries. But I would prefer that `@media` tested for and then CSS rules applied, removing `@media` queries. For example, my CSS contains:

```css
html{
  line-height: 1.5;

  @media only screen and (min-width: 0) {
    font-size: 14px;
  }

  @media only screen and (min-width: $medium-screen) {
    font-size: 14.5px;
  }

  @media only screen and (min-width: $large-screen) {
    font-size: 15px;
  }

  font-family: "Roboto", sans-serif;
  font-weight: normal;
  color: $off-black;
}
```

I would like to define some way to say that juice should apply media for screen and with min-width 1000. And then `font-size: 15px;` would be applied inline to `html`.
