### ISSUE TITLE
preserve vendor prefixes

### ISSUE THREAD

**Issue by chovy** [Automattic/juice#27]
Is it possible to preserve vendor prefixes? It seems all of my gradients are stripped out, down to just linear-gradient() and filter:..

I'm using the gradient generator here: http://www.colorzilla.com/gradient-editor/
I need to preserve -webkit, etc.

This:
```
background: #ffffff; background: -moz-linear-gradient(top,  #ffffff 0%, #e5e5e5 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ffffff), color-stop(100%,#e5e5e5)); background: -webkit-linear-gradient(top,  #ffffff 0%,#e5e5e5 100%); background: -o-linear-gradient(top,  #ffffff 0%,#e5e5e5 100%); background: -ms-linear-gradient(top,  #ffffff 0%,#e5e5e5 100%); background: linear-gradient(to bottom,  #ffffff 0%,#e5e5e5 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#e5e5e5',GradientType=0 ); ```
```
is stripped down to this:

```
background: linear-gradient(to bottom,  #ffffff 0%,#e5e5e5 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr=#ffffff, endColorstr=#e5e5e5,GradientType=0 );
```

**Comment by stevenvachon** [comment]
use autoprefixer

**Comment by bago** [comment]
Fixing this issue requires 2 major changes:
1) Move away from CSSOM and use a parser that actually gives us multiple occourences of the same property being declared multiple times with multiple value)
2) Alter Juice behaviour so to be able to keep multiple occourences of the same property: this is controversial because many times it does inline a lot of "useless" stuff, but I like "styliner" behaviour that does inline multiple occourences only if they are declared in the same "rule".

The first issue is easily fixed by #215 , now I'm working on the second one.

```css
.selector {
  background: #ffffff;
  background: -moz-linear-gradient(top,  #ffffff 0%, #e5e5e5 100%);
  background: linear-gradient(to bottom,  #ffffff 0%,#e5e5e5 100%);
}
```
Would correclty inline the 3 background properties while
```css
.selector {
  background: #ffffff;
  background: -moz-linear-gradient(top,  #ffffff 0%, #e5e5e5 100%);
}
.selector {
  background: linear-gradient(to bottom,  #ffffff 0%,#e5e5e5 100%);
}
```
Would only inline the last background, because it is on a separate rule.

Does this make sense to you?
i
