### ISSUE TITLE
preserveFontFaces is not working for me.

### ISSUE THREAD

**Issue by ArmanGrewal** [Automattic/juice#275]
Hi,
I am using "grunt-inline-css": "0.1.5" grunt plugin preserveFontFaces : true is not preserving the font faces for me.
grunt code -

```javascript
	inlinecss: {
			main: {
				options: {
					webResources: {
                        images: false,
                    },
					preserveMediaQueries: true,
					preserveFontFaces: true
				},
				files: [{
					expand: true,
					cwd: '{cwd}',
					src: ['**index**.html'],
					dest: {dest}'
				}]
			}
		},
```

css -
```css
<style>
@font-face {
				font-family: 'Titillium Web';
				font-style: normal;
				font-weight: 300;
				src: local('Titillium Web Light'), local('TitilliumWeb-Light'), url(https://fonts.gstatic.com/s/titilliumweb/v5/anMUvcNT0H1YN4FII8wpr9INifKjd1RJ3NxxEi9Cy2w.woff2) format('woff2');
				unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
				}
</style>
```
-Thanks
