### ISSUE TITLE
bug: not ignoring pseudos

### ISSUE THREAD

**Issue by andrewrk** [Automattic/juice#32]
Input:

``` css
a:link, a:visited {
  font-weight: bold;
}
```

``` html
<html><body>
<a href="#">Test</a>
</body></html>
```

Expected:

``` html
<html><body>
<a href="#">Test</a>
</body></html>
```

Actual

``` html
<html><body>
<a href="#" style="font-weight: bold;">Test</a>
</body></html>
```
