### ISSUE TITLE
Dark-Mode in emailing (with juice)

### ISSUE THREAD

**Issue by kornelion** [Automattic/juice#469]
Hi there,

I'm looking in a way to preserve the way dark-mode css code with juice for emailing generation. 

In emailing, we have to cope with different email platforms, each handling the dark-mode differently. 

While the @media (prefers-color-scheme) is working fine, we need to use other element to make it work with Microsoft Outlook for example : 

```css
[data-ogsc] .text{
 color: #ffffff!important;
}
``` 
And 
```css
[data-ogsb] .text{
 color: #ffffff!important;
}
``` 

But those declarations are stripped of when juice does its thing. 

Any indication or update that can be made to avoid this ?
Thanks !
